repos:
  - repo: local
    hooks:
      - id: validate-adrs
        name: Validate ADRs
        entry: bash scripts/validate_adrs.sh docs/ADR
        language: system
        files: ^docs/ADR/ADR-.*\.md$
