repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--format, colored, -s]
  - repo: local
    hooks:
      - id: validate-metadata
        name: Validate HESTIA metadata
        entry: .venv/bin/python hestia/tools/validate_metadata.py
        language: system
        pass_filenames: false
