name: "BB-8 Home Assistant Add-on"
description: "Home Assistant add-on for controlling Sphero BB-8 via BLE and MQTT."
version: "0.3.3"
slug: "beep_boop_bb8"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
privileged:
  - SYS_RAWIO
  - NET_ADMIN
  - SYS_ADMIN
host_dbus: true
uart: true
devices:
  - /dev/hci0
options:
  ble_adapter: hci0
  bb8_mac: "ED:ED:87:D7:27:50"
  mqtt_broker: "192.168.0.129"
  mqtt_username: "mqtt_bb8"
  mqtt_password: "mqtt_bb8"
  mqtt_topic_prefix: "bb8"
schema:
  ble_adapter: str
  bb8_mac: str
  mqtt_broker: str
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
