name: "BB-8 Home Assistant Add-on"
description: "Home Assistant add-on for controlling Sphero BB-8 via BLE and MQTT."
version: "0.1.0"
slug: "beep_boop_bb8"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
privileged:
  - SYS_RAWIO
  - NET_ADMIN
  - SYS_ADMIN
host_dbus: true
uart: true
devices:
  - /dev/hci0
options:
  ble_adapter: hci0
  bb8_mac: "00:00:00:00:00:00"
  mqtt_broker: "mqtt://localhost"
  mqtt_username: "user"
  mqtt_password: "pass"
  mqtt_topic_prefix: "bb8"
schema:
  ble_adapter: str
  bb8_mac: str
  mqtt_broker: str
  mqtt_username: str
  mqtt_password: str
  mqtt_topic_prefix: str
