name: "BB-8 BLE/MQTT Add-on"
description: "Control Sphero BB-8 via BLE with MQTT discovery"
version: "2025.08.15"
slug: "beep_boop_bb8"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
host_dbus: true
udev: true
apparmor: false
privileged:
  - NET_ADMIN
uart: true
devices:
  - /dev/hci0
options:
  # --- Telemetry & Logging ---
  enable_bridge_telemetry: false
  discovery_retain: false
  log_path: "/addons/local/beep_boop_bb8/reports/ha_bb8_addon.log"

  # --- Device Identification ---
  bb8_mac: "ED:ED:87:D7:27:50"
  bb8_name: "S33 BB84 LE"
  scan_seconds: 5
  rescan_on_fail: true
  cache_ttl_hours: 24
  ble_adapter: hci0

  # --- MQTT Configuration ---
  mqtt_broker: 192.168.0.129
  mqtt_port: 1883
  mqtt_username: mqtt_bb8
  mqtt_password: mqtt_bb8
  mqtt_topic_prefix: bb8
  ha_discovery_topic: homeassistant
  mqtt_tls: false

schema:
  # --- Telemetry & Logging ---
  enable_bridge_telemetry: bool
  discovery_retain: bool
  log_path: "str?"

  # --- Device Identification ---
  bb8_mac: "str"
  bb8_name: "str?"
  scan_seconds: "int?"
  rescan_on_fail: "bool?"
  cache_ttl_hours: "int?"
  ble_adapter: "str?"

  # --- MQTT Configuration ---
  mqtt_broker: "str"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_topic_prefix: "str"
  ha_discovery_topic: "str"
  mqtt_tls: "bool?"
