name: "BB-8 BLE/MQTT Add-on"
description: "Control Sphero BB-8 via BLE with MQTT discovery"
version: "2025.8.5"
slug: "bb8_addon"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
privileged:
  - SYS_RAWIO
  - NET_ADMIN
  - SYS_ADMIN
host_dbus: true
uart: true
devices:
  - /dev/hci0
options:
  # Optional override. When empty/omitted, add-on will auto-discover.
  bb8_mac: ""
  # BLE discovery window in seconds (used when override/cache absent or invalid)
  scan_seconds: 5
  # If an override or cached MAC fails to connect, do a one-time scan and retry
  rescan_on_fail: true
  # Hours before a cached MAC is considered stale; 0 disables TTL
  cache_ttl_hours: 720
schema:
  bb8_mac:
    type: str
    required: false
    default: ""
  scan_seconds:
    type: int
    required: false
    default: 5
  rescan_on_fail:
    type: bool
    required: false
    default: true
  cache_ttl_hours:
    type: int
    required: false
    default: 720

privileges:
  - NET_ADMIN
  - SYS_ADMIN
