name: "BB-8 BLE/MQTT Add-on"
description: "Control Sphero BB-8 via BLE with MQTT discovery"
version: "2025.8.11"
slug: "bb8_addon"
startup: application
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
boot: auto
host_dbus: true
udev: true
apparmor: false
privileged:
  - NET_ADMIN
uart: true
devices:
  - /dev/hci0
options:
  bb8_mac: ""
  scan_seconds: 5
  rescan_on_fail: true
  cache_ttl_hours: 24
  mqtt_broker: core-mosquitto
  mqtt_port: 1883
  mqtt_username: null
  mqtt_password: null
  mqtt_topic_prefix: bb8
  mqtt_tls: false
  ble_adapter: hci0
schema:
  bb8_mac: "str"
  scan_seconds: "int?"
  rescan_on_fail: "bool?"
  cache_ttl_hours: "int?"
  mqtt_broker: "str"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_topic_prefix: "str"
  mqtt_tls: "bool?"
  ble_adapter: "str?"
