[tool.pyright]
include = ["bb8_core"]
extraPaths = ["."]

[tool.ruff]

[tool.ruff.lint]
extend-select = ["F", "E", "W", "I", "N"]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
strict_optional = true
warn_unused_ignores = true
no_implicit_optional = true
