# packages/oom_guard.yaml
homeassistant:
  customize: {}

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent

template:
  - trigger:
      - platform: state
        entity_id: sensor.memory_use_percent
    sensor:
      - name: "oom_memory_use_percent"
        unit_of_measurement: "%"
        state: "{{ states('sensor.memory_use_percent') | float(0) }}"
        availability: "{{ states('sensor.memory_use_percent') not in ['unknown','unavailable','none',''] }}"

input_number:
  oom_threshold_percent:
    name: OOM threshold (%)
    min: 50
    max: 99
    step: 1
    mode: box
    unit_of_measurement: "%"
    icon: mdi:memory
    initial: 90

automation:
  - id: oom_notice_when_high_5min
    alias: "OOM: persistent notice when memory high for 5m"
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.oom_memory_use_percent
        above: "{{ states('input_number.oom_threshold_percent') | float(90) }}"
        for: "00:05:00"
    action:
      - service: persistent_notification.create
        data:
          title: "High Memory Use"
          message: >
            Memory above {{ states('input_number.oom_threshold_percent') }}% for 5m.
            Current: {{ states('sensor.oom_memory_use_percent') }}%.
            Review add-ons/integrations (Matter, DB, media, diagnostics).
