---
# ══════════════════════════════════════════════════════════════════
# ⟫⟫ SONOS ALARM  •  Customizable Bedroom Music Alarm Package ◀
# ⟫⟫ configuration.yaml  •  packages: !include_dir_named integrations
# ⟫⟫ Tier: γ  •  Domain: automation  •  Created: 2025-06-14
# ══════════════════════════════════════════════════════════════════

# ═══ Input Helpers ═══
input_boolean:
  sonos_alarm_enable:
    name: "Enable Alarm"
    initial: off
  sonos_alarm_oneoff:
    name: "One-Off Mode"
  sonos_alarm_include_group:
    name: "Include Linked Zones"
input_datetime:
  sonos_alarm_time:
    name: "Alarm Time"
    has_time: true
    has_date: false
input_select:
  sonos_alarm_zone:
    name: "Target Sonos Zone"
    options:
      - "media_player.bedroom_sonos_surround"
      - "media_player.bedroom_sonos_ray"
      - "media_player.ensuite_sonos_roam"
  sonos_alarm_recurrence:
    name: "Recurrence"
    options:
      - "DAILY"
      - "WEEKDAYS"
      - "WEEKENDS"
      - "ONCE"
    icon: mdi:alarm-check
input_number:
  sonos_alarm_volume:
    name: "Alarm Volume"
    min: 0.0
    max: 1.0
    step: 0.05

# ═══ Template Sensors & Binary Sensors ═══

template:
  - sensor:
      - name: "Sonos Alarm Profile"
        unique_id: "sonos_alarm_profile"
        state: "{{ 'active' if is_state('input_boolean.sonos_alarm_enable', 'on') else 'inactive' }}"
        attributes:
          time: "{{ states('input_datetime.sonos_alarm_time') }}"
          zone: "{{ states('input_select.sonos_alarm_zone') }}"
          volume: "{{ states('input_number.sonos_alarm_volume') | float }}"
          include_linked_zones: "{{ is_state('input_boolean.sonos_alarm_include_group', 'on') }}"
          profile_summary: >-
            {{ states('input_select.sonos_alarm_zone') | replace('media_player.', '') | replace('_', ' ') | title }}
            @ {{ states('input_datetime.sonos_alarm_time') }},
            Volume: {{ states('input_number.sonos_alarm_volume') }},
            Group: {{ 'Yes' if is_state('input_boolean.sonos_alarm_include_group', 'on') else 'No' }},
            Status: {{ 'Enabled' if is_state('input_boolean.sonos_alarm_enable', 'on') else 'Disabled' }}

  - binary_sensor:
      - name: "Sonos Alarm 30 Min Passed"
        unique_id: "sonos_alarm_30_min_passed"
        state: >
          {% set alarm_time = states('input_datetime.sonos_alarm_time') %}
          {% if alarm_time %}
            {% set t = now().replace(second=0, microsecond=0) %}
            {% set a = today_at(alarm_time) %}
            {{ (t >= a + timedelta(minutes=30)) and is_state('input_boolean.initiate_morning_sequence', 'off') }}
          {% else %}
            false
          {% endif %}
        attributes:
          description: "Calculates time delta from current time to alarm time"
          tier: ""
  # ⟫⟫ Use sonos.update_alarm to change alarm_id: X slot with dynamic values ════

automation:
  - alias: "Update Sonos Alarm (Automation)"
    id: "update_sonos_alarm_automation_001"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.sonos_alarm_enable
          - input_datetime.sonos_alarm_time
          - input_select.sonos_alarm_zone
          - input_number.sonos_alarm_volume
          - input_boolean.sonos_alarm_include_group
          - input_select.sonos_alarm_recurrence
    action:
      - variables:
          zone: "{{ states('input_select.sonos_alarm_zone') }}"
          recur: "{{ states('input_select.sonos_alarm_recurrence') }}"
          alarm_id_map:
            ONCE: 17
            DAILY: 8
            WEEKDAYS: 1
            WEEKENDS: 30
      - service: sonos.update_alarm
        data:
          entity_id: "{{ zone }}"
          alarm_id: "{{ alarm_id_map[recur] }}"
          volume: "{{ states('input_number.sonos_alarm_volume') | float(0.3) }}"
          time: "{{ states('input_datetime.sonos_alarm_time') or '07:00:00' }}"
          enabled: "{{ is_state('input_boolean.sonos_alarm_enable', 'on') }}"
          include_linked_zones: "{{ is_state('input_boolean.sonos_alarm_include_group', 'on') }}"

  - alias: "Send Sonos Alarm Preview Notification"
    id: "send_sonos_alarm_preview_notification_001"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.sonos_alarm_enable
        to: "on"
    action:
      - service: notify.mobile_app_ephone_uk
        data:
          title: "Sonos Alarm Scheduled"
          message: >
            Alarm set for {{ states('input_datetime.sonos_alarm_time') }}
            on {{ states('input_select.sonos_alarm_zone') | replace('media_player.', '') }},
            volume {{ states('input_number.sonos_alarm_volume') }},
            group: {{ 'Yes' if is_state('input_boolean.sonos_alarm_include_group', 'on') else 'No' }}.
          data:
            actions:
              - action: "disable_alarm"
                title: "Disable Alarm"
              - action: "resend_alarm"
                title: "Reconfirm"

  - alias: "Disable Sonos Alarm via Notification"
    id: "disable_sonos_alarm_via_notification_001"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: disable_alarm
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.sonos_alarm_enable

  - alias: "Reconfirm Alarm via Notification"
    id: "reconfirm_alarm_via_notification"
    trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: resend_alarm
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.initiate_morning_sequence
      - service: script.reapply_sonos_alarm

  - alias: "Auto Trigger Morning Sequence After Alarm"
    id: "auto_trigger_morning_sequence_after_alarm"
    trigger:
      - platform: state
        entity_id: binary_sensor.sonos_alarm_30_min_passed
        to: "on"
    condition:
      - condition: state
        entity_id: input_boolean.sonos_alarm_enable
        state: "on"
      - condition: state
        entity_id: input_boolean.initiate_morning_sequence
        state: "off"
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.initiate_morning_sequence
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.sonos_alarm_30_min_passed
