#══════════════════════════════════════════════════════════════════════════════
# ⟫⟫ PLAYSTATION 4  •  Recent Games → Selector + Action
# ⟫⟫ Dependencies: /config/.ps4-games.BC60A7454CD9_10e7.json, script.matrix_control
#══════════════════════════════════════════════════════════════════════════════

# ── Sensor: parse titles from the PS4 JSON file via python script ──
command_line:
  - sensor:
      name: "PS4 Recent Games"
      unique_id: ps4_recent_games
      scan_interval: 300
      command_timeout: 10
      command: >-
        python3 /config/python_scripts/ps4_recent_games.py
        /config/.ps4-games.BC60A7454CD9_10e7.json 4
      value_template: >-
        {{ value_json.first.title
           if value_json is mapping and value_json.first is mapping and 'title' in value_json.first
           else 'No games' }}
      json_attributes:
        - count
        - first
        - games
        - titles
        - images

# ── Template entities (images + buttons), with shared refresh triggers ──
template:
  - trigger:
      # Update when the recent list changes…
      - platform: state
        entity_id: sensor.ps4_recent_games
      # …and give it a periodic bump just in case
      - platform: time_pattern
        minutes: "/30"
    # --- Cover art images (fallback to a local placeholder) ---
    image:
      - name: "PS4 – Recent #1 Art"
        unique_id: ps4_recent_art_1
        url: >-
          {% set games = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ games[0]['image'] if games|count > 0 and games[0] is mapping and 'image' in games[0] and games[0]['image'] else '/media/ps-placeholder.png' }}

      - name: "PS4 – Recent #2 Art"
        unique_id: ps4_recent_art_2
        url: >-
          {% set games = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ games[1]['image'] if games|count > 1 and games[1] is mapping and 'image' in games[1] and games[1]['image'] else '/media/ps-placeholder.png' }}

      - name: "PS4 – Recent #3 Art"
        unique_id: ps4_recent_art_3
        url: >-
          {% set games = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ games[2]['image'] if games|count > 2 and games[2] is mapping and 'image' in games[2] and games[2]['image'] else '/media/ps-placeholder.png' }}

      - name: "PS4 – Recent #4 Art"
        unique_id: ps4_recent_art_4
        url: >-
          {% set games = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ games[3]['image'] if games|count > 3 and games[3] is mapping and 'image' in games[3] and games[3]['image'] else '/media/ps-placeholder.png' }}

    # --- One-tap “recent game” selection buttons ---
    button:
      # Slot 1
      - name: >-
          {% set g = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ g[0]['title'] if g|count > 0 and g[0] is mapping and 'title' in g[0] else 'PS4 – Slot 1' }}
        unique_id: ps4_btn_recent_1
        icon: mdi:sony-playstation
        press:
          - variables:
              g: "{{ state_attr('sensor.ps4_recent_games','games') or [] }}"
          - condition: template
            value_template: "{{ g|count > 0 and g[0] is mapping }}"
          - variables:
              sel: "{{ g[0] }}"
          - service: script.ps4_on_game_selected
            data:
              game: "{{ sel }}"

      # Slot 2
      - name: >-
          {% set g = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ g[1]['title'] if g|count > 1 and g[1] is mapping and 'title' in g[1] else 'PS4 – Slot 2' }}
        unique_id: ps4_btn_recent_2
        icon: mdi:sony-playstation
        press:
          - variables:
              g: "{{ state_attr('sensor.ps4_recent_games','games') or [] }}"
          - condition: template
            value_template: "{{ g|count > 1 and g[1] is mapping }}"
          - variables:
              sel: "{{ g[1] }}"
          - service: script.ps4_on_game_selected
            data:
              game: "{{ sel }}"

      # Slot 3
      - name: >-
          {% set g = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ g[2]['title'] if g|count > 2 and g[2] is mapping and 'title' in g[2] else 'PS4 – Slot 3' }}
        unique_id: ps4_btn_recent_3
        icon: mdi:sony-playstation
        press:
          - variables:
              g: "{{ state_attr('sensor.ps4_recent_games','games') or [] }}"
          - condition: template
            value_template: "{{ g|count > 2 and g[2] is mapping }}"
          - variables:
              sel: "{{ g[2] }}"
          - service: script.ps4_on_game_selected
            data:
              game: "{{ sel }}"

      # Slot 4
      - name: >-
          {% set g = state_attr('sensor.ps4_recent_games','games') or [] %}
          {{ g[3]['title'] if g|count > 3 and g[3] is mapping and 'title' in g[3] else 'PS4 – Slot 4' }}
        unique_id: ps4_btn_recent_4
        icon: mdi:sony-playstation
        press:
          - variables:
              g: "{{ state_attr('sensor.ps4_recent_games','games') or [] }}"
          - condition: template
            value_template: "{{ g|count > 3 and g[3] is mapping }}"
          - variables:
              sel: "{{ g[3] }}"
          - service: script.ps4_on_game_selected
            data:
              game: "{{ sel }}"

# ── Scripts ──
script:
  ps4_prepare_av:
    alias: "PS4 – Prepare AV (A2/B2)"
    mode: single
    sequence:
      - action: script.matrix_control
        data:
          source: "Playstation 4" # maps to your A3+B3 routing in matrix_control
          turn_on_tv: true
          repeats: 1

  ps4_route_and_wake:
    alias: "PS4 – Route & Wake"
    mode: single
    fields:
      game:
        description: "Optional game title to display in the hint"
        example: "STAR WARS Jedi: Survivor™"
    sequence:
      - action: script.matrix_control
        data:
          source: "Playstation 4"
          remote: remote.bedroom_broadlink_rm3_alpha
          device: bedroom_hdmi_matrix
          tv: media_player.bedroom_tv_alpha
      - action: media_player.turn_on
        target:
          entity_id: media_player.playstation_4
      - action: persistent_notification.create
        data:
          title: "PS4 Ready"
          message: >-
            Routed A+B to **PS4** and sent power on.
            {% set t = game if game is defined and game|length > 0
                 else states('input_select.ps4_recent_game') %}
            {% if t and t != '— none —' %}
            Select **{{ t }}** on the console.
            {% endif %}

  ps4_on_game_selected:
    alias: "PS4 – On game selected"
    mode: queued
    fields:
      game:
        description: "Game object with title/image/id (dict) or plain title (string)"
    sequence:
      - variables:
          title: >-
            {% if game is mapping %}{{ game.title | default('') }}
            {% elif game is string %}{{ game }}
            {% else %}{% endif %}
      - action: script.ps4_route_and_wake
        data:
          game: "{{ title }}"

# ── Automations ──
automation:
  - alias: "PS4: Update game picker"
    id: 3e1f2a4b-5c6d-7e8f-9a0b-112233445567
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.ps4_recent_games
    action:
      - action: input_select.set_options
        target:
          entity_id: input_select.ps4_recent_game
        data:
          options: "{{ state_attr('sensor.ps4_recent_games', 'titles') or ['— none —'] }}"

  - alias: "PS4: Route HDMI on activity"
    id: 0c9b8c7d-6e5f-4a3b-2c1d-ffeeddccbbaa
    mode: restart
    trigger:
      - platform: state
        entity_id: input_select.ps4_recent_game
      - platform: state
        entity_id: sensor.ps4_recent_games
      - platform: state
        entity_id: media_player.playstation_4
        to: playing
    action:
      - service: script.ps4_prepare_av

  - alias: "PS4 – Refresh on file change"
    id: 8b7c6d5e-4f3a-2b1c-0d9e-998877665544
    trigger:
      - platform: event
        event_type: folder_watcher
        event_data:
          event_type: modified
          path: "/config/.ps4-games.BC60A7454CD9_10e7.json"
    action:
      - action: homeassistant.update_entity
        target:
          entity_id: sensor.ps4_recent_games
# ══  LOVELACE COMPONENTS ══
#
# The following Lovelace grid card section is commented out for reference only.
#
# type: grid
# columns: 3
# square: false
# cards:
#   - type: entities
#     title: PS4 – Recent
#     entities:
#       - input_select.ps4_recent_game
#
#   - type: button
#     name: Route & Wake
#     icon: mdi:sony-playstation
#     tap_action:
#       action: perform-action
#       perform_action: script.ps4_route_and_wake
#       data:
#         game: "{{ states('input_select.ps4_recent_game') }}"
#
#   - type: button
#     name: Refresh list
#     icon: mdi:refresh
#     tap_action:
#       action: perform-action
#       perform_action: homeassistant.update_entity
#       data:
#         entity_id: sensor.ps4_recent_games_titles
#type: grid
#columns: 4
#square: false
#cards:
#  - type: picture-entity
#    entity: image.ps4_recent_1_art
#    show_name: false
#    show_state: false
#    tap_action:
#      action: call-service
#      service: button.press
#      target:
#        entity_id: button.ps4_btn_recent_1
#
#  - type: picture-entity
#    entity: image.ps4_recent_2_art
#    show_name: false
#    show_state: false
#    tap_action:
#      action: call-service
#      service: button.press
#      target:
#        entity_id: button.ps4_btn_recent_2
#
#  - type: picture-entity
#    entity: image.ps4_recent_3_art
#    show_name: false
#    show_state: false
#    tap_action:
#      action: call-service
#      service: button.press
#      target:
#        entity_id: button.ps4_btn_recent_3
#
#  - type: picture-entity
#    entity: image.ps4_recent_4_art
#    show_name: false
#    show_state: false
#    tap_action:
#      action: call-service
#      service: button.press
#      target:
#        entity_id: button.ps4_btn_recent_4
