name: ADR Governance
on:
  pull_request:
    paths:
      - "docs/ADR/**"
  push:
    branches: [ main ]
    paths:
      - "docs/ADR/**"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
      - name: Validate ADRs
        run: bash scripts/validate_adrs.sh docs/ADR
