name: release-and-guard
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'addon/**', '.github/workflows/release-and-guard.yml' ]
jobs:
  guard_publish:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - name: Structure guard (ADR-0001 + mode)
        shell: bash
        run: |
          set -euo pipefail
          test -d addon || (echo "DRIFT:addon_missing" && exit 2)
          test -f addon/config.yaml || (echo "DRIFT:missing_config_yaml" && exit 3)
          if grep -Eq '^[[:space:]]*image:[[:space:]]*' addon/config.yaml; then
            echo "MODE: PUBLISH"
            grep -Eq '^[[:space:]]*version:[[:space:]]*' addon/config.yaml || (echo "DRIFT:version_missing_in_publish_mode" && exit 9)
          else
            echo "MODE: LOCAL_DEV"
            test -f addon/Dockerfile || (echo "DRIFT:dockerfile_missing_in_local_dev" && exit 10)
            echo "TOKEN: DEV_LOCAL_BUILD_FORCED"
          fi
          echo "TOKEN: STRUCTURE_OK"
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install & test
        shell: bash
        run: |
          python -m pip install -U pip wheel
          pip install -e addon
          test -f addon/requirements-dev.txt && pip install -r addon/requirements-dev.txt || true
          pytest -q -W error --maxfail=1 --cov=bb8_core --cov-report=term-missing
      - name: Publish add-on subtree (force-fast-forward)
        if: ${{ success() }}
        shell: bash
        env:
          REMOTE: git@github.com:e-app-404/ha-bb8-addon.git
          BRANCH: main
        run: |
          set -euo pipefail
          TMP="__addon_pub_tmp_${{ github.run_id }}"
          git subtree split -P addon -b "$TMP"
          git push -f "$REMOTE" "$TMP:refs/heads/$BRANCH"
          git branch -D "$TMP"
          echo "SUBTREE_PUBLISH_OK main@${{ github.sha }}"
      - name: Upload guard receipts
        uses: actions/upload-artifact@v4
        with:
          name: guard-receipts
          path: |
            ./
