name: workspace-shape
on:
  pull_request:
  push:
    branches: [ main, "**" ]
jobs:
  shape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.13" }
      - name: Shape guard
        run: |
          python3 tools/shape_guard.py
      - name: Enforce canonical import path
        run: |
          OFF=$(grep -R -n --include='*.py' -E '^[[:space:]]*(from|import)[[:space:]]+bb8_core(\.|[[:space:]]|$)' addon ops scripts || true)
          test -z "$OFF" || { echo "Forbidden imports:\n$OFF"; exit 1; }
          test ! -d bb8_core || { echo "Root-level bb8_core/ is forbidden"; exit 1; }
      - name: Repo-shape guard
        run: |
          set -euo pipefail
          test ! -d services.d || { echo "Root services.d/ forbidden"; exit 1; }
          OFF=$(grep -R -n --include='*.py' -E '(^|[^/])\b(from|import)\s+bb8_core(\.|[[:space:]]|$)' addon ops scripts tools 2>/dev/null || true)
          test -z "$OFF" || { echo "Forbidden imports:\n$OFF"; exit 1; }
          PY_AT_ROOT_TOOLS=$(find tools -maxdepth 1 -name '*.py' 2>/dev/null | wc -l | tr -d ' ')
          test "$PY_AT_ROOT_TOOLS" = "0" || { echo "tools/*.py at repo root not allowed"; exit 1; }
