name: tests
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - run: python -m pip install -U pip pytest pytest-cov pyyaml
      - run: |
          python -m compileall -q .
          pytest -q -rA --disable-warnings --maxfail=1 \
            --cov=addon --cov=addon/bb8_core \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml \
            --cov-report=json:coverage.json
      - run: python tools/coverage_gate.py coverage.xml
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            coverage.xml
            coverage.json